### ISSUE TITLE
Argument completion crash

### ISSUE THREAD

**Issue by SolitudeSF** [elves/elvish#1557] opened 2022-06-12 06:26 UTC
Invoking completion when completing argument that contains invalid elvish syntax crashes the shell.

```
 ▲ ~  asd `
goroutine 1 [running]:nteractive]: unexpected rune '`'
src.elv.sh/pkg/sys.DumpStack()
	/home/solitude/git/elvish/pkg/sys/dumpstack.go:10 +0x66
src.elv.sh/pkg/shell.handlePanic()
	/home/solitude/git/elvish/pkg/shell/interact.go:141 +0x5a
panic({0x88cf40, 0xc0005540a8})
	/home/solitude/.local/share/asdf/installs/golang/1.18/go/src/runtime/panic.go:838 +0x207
src.elv.sh/pkg/edit/complete.completeVariable({0x0?, 0x0?, 0x0?}, 0xc000128000?, {0x0?, 0x0?})
	/home/solitude/git/elvish/pkg/edit/complete/completers.go:143 +0x28f
src.elv.sh/pkg/edit/complete.Complete({{0xc00059c250?, 0xc000174000?}, 0x8?}, 0x0?, {0xc0005f91d0?, 0xc000336480?})
	/home/solitude/git/elvish/pkg/edit/complete/complete.go:71 +0x20e
src.elv.sh/pkg/edit.completionStart({0x918d58, 0xc000174000}, {0x9156c8, 0xc0001193e0}, 0x0?, {0xc0005f91d0?, 0xc000336480?}, 0x1)
	/home/solitude/git/elvish/pkg/edit/completion.go:179 +0x153
src.elv.sh/pkg/edit.initCompletion.func4()
	/home/solitude/git/elvish/pkg/edit/completion.go:265 +0x78
reflect.Value.call({0x82bf20?, 0xc0001528c0?, 0x540f4d?}, {0x8a4d7b, 0x4}, {0x0, 0x0, 0x400?})
	/home/solitude/.local/share/asdf/installs/golang/1.18/go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0x82bf20?, 0xc0001528c0?, 0x60fb27?}, {0x0, 0x0, 0x0})
	/home/solitude/.local/share/asdf/installs/golang/1.18/go/src/reflect/value.go:339 +0xbf
src.elv.sh/pkg/eval.(*goFn).Call(0xc000178150, 0xc00014aa00, {0x0, 0x0, 0x0?}, 0xc0000956e0)
	/home/solitude/git/elvish/pkg/eval/go_fn.go:247 +0xb46
src.elv.sh/pkg/eval.(*Evaler).Call(0x53e68d?, {0x914fc8, 0xc000178150}, {{0x0, 0x0, 0x0}, 0xc0000956e0, {0x8a9052, 0x10}}, {{0xc000312f18, ...}, ...})
	/home/solitude/git/elvish/pkg/eval/eval.go:442 +0x376
src.elv.sh/pkg/edit.callWithNotifyPorts({0x9165c0, 0xc00010e5a0}, 0x1?, {0x914fc8, 0xc000178150}, {0x0, 0x0, 0x0})
	/home/solitude/git/elvish/pkg/edit/key_binding.go:67 +0x1ef
src.elv.sh/pkg/edit.mapBindings.Handle({{0x9165c0, 0xc00010e5a0}, 0xc000128000, {0xc00012e630, 0x1, 0x1}}, {0xc00012e4c8?, 0xc000377708?}, {0x915588, 0xc0007b6730})
	/home/solitude/git/elvish/pkg/edit/key_binding.go:41 +0x10b
src.elv.sh/pkg/cli/tk.(*codeArea).handleKeyEvent(0xc000174100, {0x3777a0?, 0xc0?})
	/home/solitude/git/elvish/pkg/cli/tk/codearea.go:346 +0xdc
src.elv.sh/pkg/cli/tk.(*codeArea).Handle(0xc000174000?, {0x915588?, 0xc0007b6728?})
	/home/solitude/git/elvish/pkg/cli/tk/codearea.go:177 +0x72
src.elv.sh/pkg/cli.(*app).handle(0xc000174000, {0x872c40?, 0xc0007b6728})
	/home/solitude/git/elvish/pkg/cli/app.go:227 +0x165
src.elv.sh/pkg/cli.(*loop).Run(0xc000152840)
	/home/solitude/git/elvish/pkg/cli/loop.go:129 +0x1ac
src.elv.sh/pkg/cli.(*app).ReadCode(0xc000174000)
	/home/solitude/git/elvish/pkg/cli/app.go:476 +0x49a
src.elv.sh/pkg/edit.(*Editor).ReadCode(0xc000010010?)
	/home/solitude/git/elvish/pkg/edit/editor.go:113 +0x22
src.elv.sh/pkg/shell.interact(0xc000128000, {0xc000010010, 0xc000010018, 0xc000010020}, 0xc000165da8)
	/home/solitude/git/elvish/pkg/shell/interact.go:100 +0x846
src.elv.sh/pkg/shell.(*Program).Run(0xc000095ad0, {0xc000010010, 0xc000010018, 0xc000010020}, {0xc000020200, 0x0, 0x0})
	/home/solitude/git/elvish/pkg/shell/shell.go:109 +0x325
src.elv.sh/pkg/prog.composite.Run(...)
	/home/solitude/git/elvish/pkg/prog/prog.go:118
src.elv.sh/pkg/prog.Run({0xc000010010, 0xc000010018, 0xc000010020}, {0xc000020200, 0x1, 0x1}, {0x916de0, 0xc00000e690})
	/home/solitude/git/elvish/pkg/prog/prog.go:83 +0x3d4
main.main()
	/home/solitude/git/elvish/cmd/elvish/main.go:18 +0x17f

goroutine 6 [chan receive]:
src.elv.sh/pkg/eval.getBlackholeChan.func1()
	/home/solitude/git/elvish/pkg/eval/port.go:96 +0x3a
created by src.elv.sh/pkg/eval.getBlackholeChan
	/home/solitude/git/elvish/pkg/eval/port.go:95 +0x6a

goroutine 7 [syscall]:
os/signal.signal_recv()
	/home/solitude/.local/share/asdf/installs/golang/1.18/go/src/runtime/sigqueue.go:151 +0x2f
os/signal.loop()
	/home/solitude/.local/share/asdf/installs/golang/1.18/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/home/solitude/.local/share/asdf/installs/golang/1.18/go/src/os/signal/signal.go:151 +0x2a

goroutine 18 [chan receive]:
src.elv.sh/pkg/shell.initSignal.func1()
	/home/solitude/git/elvish/pkg/shell/shell.go:150 +0x85
created by src.elv.sh/pkg/shell.initSignal
	/home/solitude/git/elvish/pkg/shell/shell.go:149 +0x91

goroutine 20 [chan receive]:
src.elv.sh/pkg/cli/prompt.(*Prompt).loop(0xc000131030)
	/home/solitude/git/elvish/pkg/cli/prompt/prompt.go:77 +0xb6
created by src.elv.sh/pkg/cli/prompt.New
	/home/solitude/git/elvish/pkg/cli/prompt/prompt.go:70 +0x1bc

goroutine 21 [chan receive]:
src.elv.sh/pkg/cli/prompt.(*Prompt).loop(0xc000131110)
	/home/solitude/git/elvish/pkg/cli/prompt/prompt.go:77 +0xb6
created by src.elv.sh/pkg/cli/prompt.New
	/home/solitude/git/elvish/pkg/cli/prompt/prompt.go:70 +0x1bc

runtime error: index out of range [0] with length 0
```

**Comment by krader1961** [comment] 2022-06-12 06:31
Is that reproducible using Elvish built from HEAD? It's also not clear how to reproduce the failure given this problem statement:

> Invoking completion when completing argument that contains invalid elvish syntax crashes the shell.

It would be preferable to rewrite that as something like "type a, b, c, then x" 😄  Not to mention whether or not you can reproduce this failure without your usual *~/.config/elvish* config.

**Comment by SolitudeSF** [comment] 2022-06-12 06:40
you can see the prompt in code snippet. i can reproduce it with with HEAD.

**Comment by xiaq** [comment] 2022-06-12 14:52
Duplicate of #1530

**Closed by xiaq** 2022-06-12 14:52 UTC
