### ISSUE TITLE
Panic when attempting to access function of module that failed to load

### ISSUE THREAD

**Issue by Wizhi** [elves/elvish#1302] opened 2021-05-12 19:34 UTC
Not sure if the title properly describes the issue, sorry about that.

Steps to reproduce:

1. Attempt to load non-existing module `foo`
2. Enter `foo:b`

The crash occurs upon entering any letter after `foo:`.

**Build info**

```
[wizhi@ellinia ~]$ elvish -buildinfo
Version: 0.15.0
Go version: go1.16.3
Reproducible build: false
```

**Example**

```
~> use foo
Exception: no such module: foo
[tty 1], line 1: use foo
~> foo:panic: runtime error: invalid memory address or nil pointer dereference                                        wizhi@ellinia
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55f5adfa3568]

goroutine 4925 [running]:
github.com/elves/elvish/pkg/eval.(*Ns).lookup(0x0, 0xc0005aacf8, 0x2, 0x2)
	github.com/elves/elvish/pkg/eval/ns.go:101 +0x28
github.com/elves/elvish/pkg/eval.(*Ns).IndexName(...)
	github.com/elves/elvish/pkg/eval/ns.go:93
github.com/elves/elvish/pkg/eval.(*Ns).Index(0x0, 0x55f5ae237b80, 0xc0005aad18, 0x55f5ae00501e, 0x1, 0xc0005aacf8)
	github.com/elves/elvish/pkg/eval/ns.go:80 +0x5c
github.com/elves/elvish/pkg/edit.hasFn(0x0, 0xc000629a14, 0x1, 0x1)
	github.com/elves/elvish/pkg/edit/highlight.go:97 +0x9d
github.com/elves/elvish/pkg/edit.hasQualifiedFn(0xc000212c30, 0xc000629a10, 0x4, 0xc000629a14, 0x1, 0x1)
	github.com/elves/elvish/pkg/edit/highlight.go:93 +0x1ca
github.com/elves/elvish/pkg/edit.hasCommand(0xc000212c30, 0xc000629a10, 0x5, 0x0)
	github.com/elves/elvish/pkg/edit/highlight.go:58 +0x11d
github.com/elves/elvish/pkg/edit.initHighlighter.func2(0xc000629a10, 0x5, 0x1)
	github.com/elves/elvish/pkg/edit/highlight.go:17 +0x45
github.com/elves/elvish/pkg/edit/highlight.highlight.func1(0xc00000e688, 0x1, 0x1, 0xc000338378, 0x1, 0x1, 0xc00009fc50, 0xc00009f)
	github.com/elves/elvish/pkg/edit/highlight/highlight.go:104 +0xe3
created by github.com/elves/elvish/pkg/edit/highlight.highlight
	github.com/elves/elvish/pkg/edit/highlight/highlight.go:100 +0xc05
```

**Comment by krader1961** [comment] 2021-05-12 19:59
This is a duplicate of #1257.

**Closed** 2021-05-12 20:02 UTC
