### ISSUE TITLE
Error consistency: `count` returns a unique error for an invalid number of arguments

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#966] opened 2020-04-15 04:02 UTC
I started implementing the `math:max` command by copying the builtin `count` implementation. Which resulted in me noticing that is the only builtin that returns `errors.New("want 0 or 1 argument")` if it gets more than one argument. Similar commands return `eval.ErrArgs` or `arity mismatch`. For example,

```
> one a b
Exception: arity mismatch: arguments here must be 0 to 1 values, but is 2 values
[tty], line 1: one a b
```

It's not clear why `count` has a unique error. This looks like a historical artifact that should be normalized to be consistent with other commands. It seems to me `func count` should be using `eval.Inputs` rather than an explicit variadic arg. Yes? No?

**Comment by xiaq** [comment] 2020-04-15 23:09
Re the unique error: Yes, it is a historical artifact and should be changed to use `errs.ArityMismatch`.

Re algorithm: See my comment in #968.

**Comment by xiaq** [comment] 2020-04-15 23:18
Re your comment in the PR: adding some comments explaining why `count` does not use `Inputs` is definitely useful, and so is adding more tests.

Also note that I am adding error tests to be more rigorous: search `.Throws(` in pkg/eval and you will see that they test the structure of the cause, as well as stack traces. This is a pattern I am moving to and I eventually plan to remove support for `.ThrowsAny()` and `.ThrowsMessage()`.

**Comment by krader1961** [comment] 2020-04-16 01:43
I'm not thrilled by `.ThrowsMessage()` but it's certainly useful as a stepping stone to making it easier to match `error()` (and `fmt.Errorf()`) vars that helps ensure a test is validating the actual exception that is expected. Long term it seems to me that expanding the error types in *pkg/eval/errs/errs.go* and using those rather than Go's `error` type is preferable.

**Closed** 2020-04-16 14:56 UTC

**Comment by xiaq** [comment] 2020-04-17 21:12
@krader1961 The stepping stone argument is spot-on - we still need it to test against cases that do not have structured errors yet.
