### ISSUE TITLE
Crash in editor when moving cursor left in a background job

### ISSUE THREAD

**Issue by notramo** [elves/elvish#701] opened 2018-06-20 14:54 UTC
```elvish
# <function> is any function e.g. move-dot-left, kill-word-left
{ sleep 1; edit:<function> }&
```
It crashes if the cursor is on the end of the buffer content.

os: Arch Linux 4.17.2-1-ARCH
version: 0.11-305-g7be51575

**Comment by xiaq** [comment] 2018-07-02 23:01
I know the editor is not concurrency-safe, but I cannot reproduce this one. Is it still happening in HEAD? Can you give me more detailed reproduction steps?

**Comment by notramo** [comment] 2018-07-03 18:34
It's more complicated than I thought.
Tested on `HEAD`.
Detailed steps to reproduce:
1. launch the command I wrote earlier
2. enter some text
3. after the background job finishes, enter some text again
4. recovery shell is opened

A few detail I discovered later:
- The cursor has to move left in the background (`kill-rune-left`, `move-dot-left-word`, `move-dot-left`).
  Moving it right works properly.
- After the background job returned, the first keypress have to insert some text to crash the shell. Deleting with `Backspace`, or moving cursor works properly. Entering new line with `Alt+Return` also works properly, however it inserts into the buffer.
- If the first keypress was something that works, it don't crash even if text is inserted later.
- `{ sleep 2; edit:move-dot-left; edit:insert-at-dot <text> } &` inserts the given text into the buffer properly, but it don't prevents the crash after the job returned.

**Comment by xiaq** [comment] 2018-07-08 21:24
Thanks, I was able to reproduce it this time. The particular reproduction procedure I used was:

1. Run `{ sleep 2; edit:move-dot-left } &`;
2. Within the two seconds, type `x`;
3. Wait to make sure that two seconds have passed, type another `x`;
4. Crash.

Looking at the stack trace, it seems to have something to do with the abbreviation expansion code.

**Comment by xiaq** [comment] 2018-07-08 21:46
OK, I know the reason why this crash is happening now. The abbreviation expansion functionality depends on maintaining the `literalInserts` field of the `insert` struct

https://github.com/elves/elvish/blob/99687f337442f07c0dd6959103b34c450300dce7/edit/edcore/insert.go#L64-L65

This maintenance is done in the editor's main loop:

https://github.com/elves/elvish/blob/99687f337442f07c0dd6959103b34c450300dce7/edit/edcore/edit.go#L501-L505

But that is not correct. When an editor function is invoked anywhere else this code path is not triggered.

**Comment by xiaq** [comment] 2018-07-08 21:49
Since I am working on a rewrite of the line editor, I will probably not fix this soon but rather take this into account in the rewrite.

**Comment by xiaq** [comment] 2020-01-14 13:16
Fixed in the new editor!

**Closed by xiaq** 2020-01-14 13:16 UTC
Labels: A:Editor, t:bug
