### ISSUE TITLE
Rpmlint reported `elvish.x86_64: E: readelf-failed /usr/bin/elvish 'utf-8' codec can't decode byte 0xc2 in position 7599: invalid continuation byte` when building on Fedora

### ISSUE THREAD

**Issue by topazus** [elves/elvish#1793] opened 2024-04-22 11:18 UTC
### What happened, and what did you expect to happen?

partial rpmlint output from [review.txt](https://download.copr.fedorainfracloud.org/results/topazus/test-review/fedora-rawhide-x86_64/07335299-elvish/fedora-review/review.txt)
```
Rpmlint
-------
Checking: elvish-0.20.1-1.fc41.x86_64.rpm
          elvish-0.20.1-1.fc41.src.rpm
============================ rpmlint session starts ============================
rpmlint: 2.5.0
configuration:
    /usr/lib/python3.12/site-packages/rpmlint/configdefaults.toml
    /etc/xdg/rpmlint/fedora-legacy-licenses.toml
    /etc/xdg/rpmlint/fedora-spdx-licenses.toml
    /etc/xdg/rpmlint/fedora.toml
    /etc/xdg/rpmlint/scoring.toml
    /etc/xdg/rpmlint/users-groups.toml
    /etc/xdg/rpmlint/warn-on-functions.toml
rpmlintrc: [PosixPath('/tmp/tmp1xad3qyx')]
checks: 32, packages: 2

elvish.x86_64: E: readelf-failed /usr/bin/elvish 'utf-8' codec can't decode byte 0xc2 in position 7599: invalid continuation byte
elvish.x86_64: W: no-manual-page-for-binary elvish
elvish.x86_64: W: files-duplicate /usr/share/licenses/elvish/vscode-LICENSE /usr/share/licenses/elvish/LICENSE
elvish.x86_64: W: files-duplicate /usr/share/licenses/elvish/pkg-rpc-LICENSE /usr/share/licenses/elvish/pkg-diff-LICENSE
 2 packages and 0 specfiles checked; 1 errors, 3 warnings, 7 filtered, 1 badness; has taken 0.3 s 
```

detailed build log: https://download.copr.fedorainfracloud.org/results/topazus/test-review/fedora-rawhide-x86_64/07335299-elvish/builder-live.log.gz

### Output of "elvish -version"

0.20.1

### Code of Conduct

- [X] I agree to follow Elvish's [Code of Conduct](https://src.elv.sh/CODE_OF_CONDUCT.md).

**Comment by xiaq** [comment] 2024-04-22 11:43
Hmm, seems to be something specific to Fedora's builder? Not sure what `readelf` is looking for in the binary, but Elvish should be buildable like other Go applications.

**Comment by xiaq** [comment] 2024-04-22 12:08
Chatted elsewhere and it does seem to be Fedora packaging-specific thing, so I'll close this for now. Feel free to re-open if it turns out to be caused by something in Elvish.

**Closed by xiaq** 2024-04-22 12:08 UTC
