### ISSUE TITLE
Multiple data races 

### ISSUE THREAD

**Issue by dcu** [elves/elvish#623] opened 2018-03-07 13:27 UTC
when running `go run -race main.go` I can see multiple data races

for example:

```
==================
WARNING: DATA RACE
Write at 0x00c420188630 by goroutine 34:
  runtime.mapassign_faststr()
      /usr/local/Cellar/go/1.10/libexec/src/runtime/hashmap_fast.go:694 +0x0
  github.com/elves/elvish/eval.varOp.Invoke()
```

and 

```
==================
WARNING: DATA RACE
Write at 0x00c4203bd760 by goroutine 104:
  github.com/elves/elvish/eval/vars.any.Set()
      /Users/dcuadrado/Projects/GoCode/src/github.com/elves/elvish/eval/vars/any.go:8 +0x38
  github.com/elves/elvish/eval.(*assignmentOp).Invoke()
```

**Comment by xiaq** [comment] 2018-03-08 04:44
It is quite likely that Elvish has data races, but I cannot reproduce this with my setup; do you have something in your `rc.elv`? Can you reproduce this with an empty `rc.elv`. It is also possible that `-race` is broken on macOS though.

**Comment by dcu** [comment] 2018-03-08 12:59
With the latest changes the data races have been reduce to one that is indeed triggered by something in my `rc.elv`. I'll try to find the culprit and report back

I've used `-race` on both OSX and Linux and it works well.

**Comment by dcu** [comment] 2018-03-08 13:31
it is caused by this code in my `rc.elv`

```
-bundler-cmds = [
    (re:find '  bundle (\w+)' (error = ?(e:bundle --help 2>&1|slurp)) | each [x]{ put $x[groups][1][text] })
]
```

**Comment by krader1961** [comment] 2020-04-10 03:52
FWIW, Using the current source at the time I type this I can reproduce the race using Go 1.14.0 on macOS. I ran `go run -race main.go` then pasted the following at the shell prompt:

```
-bundler-cmds = [
    (re:find '  bundle (\w+)' (error = ?(e:bundle --help 2>&1|slurp)) | each [x]{ put $x[groups][1][text] })
]
```

The details have, understandably, changed given the passage of two years. This might be related to issue #888. The issue in this case is that instantiating a new local var is racing with resolving a var in the `(type Frame).local` namespace map.

```
WARNING: DATA RACE
Write at 0x00c0001a26c0 by goroutine 105:
  runtime.mapassign_faststr()
      /usr/local/Cellar/go/1.14/libexec/src/runtime/map_faststr.go:202 +0x0
  github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke()
      /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:87 +0x250
  github.com/elves/elvish/pkg/eval.effectOp.exec()
      /Users/krader/projects/3rd-party/elvish/pkg/eval/op.go:33 +0xec
...

Previous read at 0x00c0001a26c0 by goroutine 75:
  runtime.mapaccess1_faststr()
      /usr/local/Cellar/go/1.14/libexec/src/runtime/map_faststr.go:12 +0x0
  github.com/elves/elvish/pkg/eval.resolveNested()
      /Users/krader/projects/3rd-party/elvish/pkg/eval/resolve.go:128 +0x19f
  github.com/elves/elvish/pkg/eval.(*Frame).resolveNonPseudo()
      /Users/krader/projects/3rd-party/elvish/pkg/eval/resolve.go:103 +0x6b
  github.com/elves/elvish/pkg/eval.(*Frame).ResolveVar()
      /Users/krader/projects/3rd-party/elvish/pkg/eval/resolve.go:96 +0xa5
...
```

Whether adding a mutex to guard references to `(type Frame).local` is the right solution or something more subtle is appropriate is TBD.

**Comment by xiaq** [comment] 2020-04-21 10:16
This is a very different issue from #888. This problem in this issue violates Go's memory model and breaches memory safety, while #888 is not problematic at all from the perspective of the Go runtime.

**Comment by krader1961** [comment] 2020-04-25 04:11
> This is a very different issue from #888.

That is true. I shouldn't have used the phrase "might be related to". However, to a user of Elvish that is a very subtle distinction. Just because the examples in issue #888 don't trigger a fatal error in the Go runtime does not mean those scenarios are fundamentally different from this one. As you noted in your [comment](https://github.com/elves/elvish/issues/888#issuecomment-569962003) this is conceptually the same problem. Only at a different level of abstraction.

**Comment by xiaq** [comment] 2020-04-26 17:04
Minimal example:

```
nop (a = 1) | nop
```

**Comment by xiaq** [comment] 2020-04-26 17:06
8c71635ca33dbea479fe37af3b2f867906ae0afd addressed the simplistic case of `a = 1 | nop` by "hoisting" the creation of all new variables that are directly within the pipeline to the start of the pipeline. That hoisting needs to be made more pervasive.

**Closed** 2020-04-26 18:07 UTC
Labels: C:Crash & Deadlock, t:bug
