### ISSUE TITLE
first opened elvish shell hangs on exit until all others are closed

### ISSUE THREAD

**Issue by CosmicToast** [elves/elvish#1191] opened 2020-12-04 18:48 UTC
How to reproduce:

1. Set up a keybind to launch elvish. (in my case, I have `chsh -s /usr/local/bin/elvish` + the foot terminal on super+enter, though the former requires a relogin)
2. Launch two terminals, each running an elvish as a login shell.
3. log out of the first terminal (using `^d`). Observe that it will not exit until the second one is logged out as well.

This seems to be related to the first elvish shell launching `elvish -daemon` when ran (unless one is already running).
However, when you try to exit it, it will stay open until no further clients remain.

I tried to remedy this by launching the daemon (with the same arguments) separately, but it appears that the daemon self-terminates once it has no more clients.

**Comment by xiaq** [comment] 2020-12-05 13:53
Which terminal are you using?

**Comment by krader1961** [comment] 2020-12-05 21:43
I can't reproduce. What Elvish version? What OS? Does it happen if you start the shells with the `-norc` option? If you `kill -USR1` the shell that hangs you should get backtraces of each goroutine. Also, Elvish doesn't actually do anything differently when run as a login shell. So you should be able to reproduce by simply starting two elvish instances from a different shell such as bash. Can you in fact do so?

**Comment by CosmicToast** [comment] 2020-12-05 22:30
> Which terminal

I'm using the [foot](https://codeberg.org/dnkl/foot) terminal (only works on wayland, though).
I host a build of it [here](https://minio.toast.cafe/bin/index.html#x86_64/c/) (link to directory because filename changes with version).

> What Elvish version?

v0.14.0-165-g6f3b8a78 
I host a build of it [here](https://minio.toast.cafe/bin/index.html#x86_64/testing/) - same story as with foot, meaning you can get my exact binary.

> What OS?

Fedora 33 x86_64 (with a 5.10.0-rc5 kernel).

> Does it happen if you start the shells with the `-norc` option?

Yes (I simulated this by opening two terminal emulators, exec-ing into another shell, and then running `foot $(which elvish) -norc`).

> (implicit) Does this happen when you do not run elvish as a login shell.

No, there's no difference whether or not I do `foot --login-shell $(which elvish)` and the above.

> You should be able to reproduce by simply starting two elvish instances from a different shell such as bash.

I actually can't...
However, if I launch the first elvish instance in foot, and then a second one from a different shell, the foot window will not close until the in-shell instance is also closed.

Further, I can also reproduce this behavior exactly with `gnome-terminal`.

> If you kill -USR1 the shell that hangs

The shell that hangs does not respond to `kill -USR1` (but the process does still exist).
`/proc/$PID/status` shows State Z (zombie).
`/proc/$PID/stack` is empty.
`/proc/$PID/syscall` shows `-1 0x0 0x0`.

**Comment by krader1961** [comment] 2020-12-05 22:38
If the state is "Z" (zombie) it means the process has terminated. It only "exists" as an entry in the process table to give the parent process the opportunity to call `wait4()` (or a related syscall) to capture the exit status of the process. So the problem is not that elvish isn't terminating it's that your terminal isn't reaping the terminated shell. Some terminals can be configured not to close when the top-level process they run terminates to make it easier to detect when the process (normally a login shell but could be anything) terminates abnormally.

**Comment by CosmicToast** [comment] 2020-12-05 23:20
> If the state is "Z" (zombie) it means the process has terminated. It only "exists" as an entry in the process table to give the parent process the opportunity to call `wait4()` (or a related syscall) to capture the exit status of the process. So the problem is not that elvish isn't terminating it's that your terminal isn't reaping the terminated shell. Some terminals can be configured not to close when the top-level process they run terminates to make it easier to detect when the process (normally a login shell but could be anything) terminates abnormally.

This obviously isn't what's happening though.
Both gnome-terminal and foot are not configured in that way, and act normally with all other shells (including bash, plan9 rc, mksh and zsh).
Further, if that was the case, it would hang whether or not I closed an entirely separate instance of elvish (whereas as of now closing the second instance allows the first one to terminate properly).

Finally, this is clearly related to the elvish daemon.
If I launch a daemon in a different shell, and then repeat the experiment, the first shell does not hang. (this cannot be used as a workaround because the elvish daemon self-terminates once there are no more sessions)

This *strongly* suggests this is related to the first shell also spawning a daemon.

**Comment by CosmicToast** [comment] 2020-12-06 00:14
To further reinforce this, consider the following:

1. Open terminal 1.
2. Open terminal 2.
3. In terminal 1, log out (`^d`). Terminal hangs.
4. In terminal 2, kill the elvish daemon (after determining what pid it has using pgrep, it's easily identifiable by the `-daemon` arg). Terminal 1 closes.

**Comment by krader1961** [comment] 2020-12-06 01:26
I still can't reproduce, but note that I'm doing my tests on macOS not Fedora Linux. The first elvish instance starts the daemon as its direct descendent. On my system when I exit that elvish instance (after starting a second elvish instance) the daemon process is reparented to PID 1. There is something weird going on in your system, @CosmicToast. If you do `ps -fp $pid` using the PID of the daemon what is its PPID value before and after you terminate the first elvish instance? The before value should be the PID of the first elvish instance and the after value should be one.

P.S., A case could be made that elvish should do a double-fork when launching the daemon to immediately detach it from the elvish process and reparent it to the init process. That should be a trivial change so I'll take a stab at a patch in a few minutes so we can see if that alters the behavior you're seeing, @CosmicToast.

**Comment by krader1961** [comment] 2020-12-06 03:50
@CosmicToast, What happens is you build Elvish with this patch:

```
diff --git a/pkg/daemon/spawn.go b/pkg/daemon/spawn.go
index fd5dca3b..a3a3ccfb 100644
--- a/pkg/daemon/spawn.go
+++ b/pkg/daemon/spawn.go
@@ -72,8 +72,10 @@ func Spawn(cfg *SpawnConfig) error {
 		"-logprefix", logPathPrefix,
 	}

-	// TODO Redirect daemon stdout and stderr
-
-	_, err := os.StartProcess(binPath, args, procAttrForSpawn())
+	procattrs := procAttrForSpawn()
+	_, err := os.StartProcess(binPath, args, procattrs)
+	// We don't want to retain a reference to a /dev/null file handle passed
+	// to the daemon.
+	procattrs.Files[0].Close()
 	return err
 }
diff --git a/pkg/daemon/spawn_unix.go b/pkg/daemon/spawn_unix.go
index e2da2b5c..568ec676 100644
--- a/pkg/daemon/spawn_unix.go
+++ b/pkg/daemon/spawn_unix.go
@@ -8,10 +8,16 @@ import (
 )

 func procAttrForSpawn() *os.ProcAttr {
+	// We don't want the daemon to have any references to the stdin, stdout,
+	// or stderr file descriptors of the original shell. We do, however, want
+	// to ensure those file descriptors are open when the daemon starts so
+	// that any file opens it performs does not bind to those three, critical,
+	// file descriptors.
+	devnull, _ := os.OpenFile("/dev/null", os.O_RDWR, 0)
 	return &os.ProcAttr{
 		Dir:   "/",        // cd to /
 		Env:   []string{}, // empty environment
-		Files: []*os.File{os.Stdin, os.Stdout, os.Stderr},
+		Files: []*os.File{devnull, devnull, devnull},
 		Sys: &syscall.SysProcAttr{
 			Setsid: true, // detach from current terminal
 		},
```

That patch is not OS agnostic since it doesn't work on MS Windows. But before going to the trouble of making it OS agnostic I would like to know if it fixes the problem you reported in this issue.

**Comment by CosmicToast** [comment] 2020-12-06 11:57
> What happens if you build Elvish with this patch

The issue gets resolved. (i.e I can no longer reproduce)

It'd also be nice to have a patch to launch the daemon standalone and not have it die as soon as it has no clients (after the first one connects).
Then I could launch one on startup and just not worry about it.
But that's separate to this issue (though it would provide a workaround for it in the meantime as well).

**Comment by krader1961** [comment] 2020-12-06 23:11
Okay, that means the problem is due to your terminal waiting for the pty to be closed; not just for the shell to terminate. You could cause the same problem in the second terminal (the one that did not start the daemon) by simply doing `sleep 99 &` before exiting the shell. Since the sleep will have its stdin/stdout open on the tty that will keep the terminal from closing. Neither macOS's native terminal app or iTerm behave that way. It's an interesting choice that your terminal chooses to wait for all open file descriptors on the pty to be closed.

**Comment by CosmicToast** [comment] 2020-12-07 00:04
This behavior is present not just on foot, but also gnome-terminal (as I mentioned).
Which in turn is VTE (a library for implementing terminal emulators that's responsible for roughly half of the ones on linux).

I'll try and test against a few others (non-VTE) tomorrow, just to see if this is just the standard way of doing things on linux.

**Comment by krader1961** [comment] 2020-12-10 04:00
> It'd also be nice to have a patch to launch the daemon standalone and not have it die as soon as it has no clients (after the first one connects).

That seems like a bad idea. Ideally the Elvish daemon would be eliminated. We definitely do not want to make it easier for people to cause problems by launching an Elvish daemon that is likely to have a different interface than a particular elvish shell.

**Comment by krader1961** [comment] 2020-12-10 04:16
@CosmicToast, Please confirm that https://github.com/elves/elvish/pull/1192 fixes your problem. It should do so since I have verified my change eliminates the inheritance of the original shell's TTY file descriptors. But I did so in an indirect manner so it is possible I have made a mistake and your scenario results in an unexpected inheritance of the stdio file descriptors.

**Comment by CosmicToast** [comment] 2020-12-10 12:26
@krader1961 seems to work fine on my end

**Closed** 2021-01-16 23:18 UTC
