### ISSUE TITLE
Include variable name in error message when setting read-only variable

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#255] opened 2016-10-11 06:58 UTC
```
~> try failed; except false; tried
<interact>:1:20: eval error: read-only; cannot be set
try failed; except false; tried
```

**Comment by xiaq** [comment] 2016-10-11 07:22
Hmm, this is because your code tries to set `$false` which is read-only.

Perhaps the error message should claim which variable it is trying to set.

**Comment by xiaq** [comment] 2016-10-11 17:32
I have clarified the error message a bit and given the word after `except` the color of variables. I hope this makes things less confusing.

I am leaving this issue open though, since ideally this message should be "$false is read-only". Unfortunately this is a bit hard to do now, since such an error message is generated in a place with no access to the variable name (https://github.com/elves/elvish/blob/ebf34e1c64786f6d62f49cdf9eadbe52277f3c1e/eval/variable.go#L54).

Had we sticked to the `error`-returning-style error handling that is typically of golang, this will be a lot easier, since the caller will likely have access to the variable name. Perhaps we should re-evaluate the benefits and drawbacks of the current approach of using `panic` and `recover` for error handling some day.

**Comment by krader1961** [comment] 2020-10-15 04:35
FWIW, This issue is still relevant although the way to reproduce it needs to be updated:

```
> try { fail } except false { put $false }
Exception: read-only variable; cannot be set
[tty 37], line 1: try { fail } except false { put $false }
```

Also, "the current approach of using panic and recover for error handling" is no longer relevant to this issue since the implementation no longer uses Go's `panic` function to implement this behavior.

**Comment by krader1961** [comment] 2020-10-16 03:36
FYI, The fix for this issue is straightforward. Simply replace the `ErrSetReadOnlyVar` var with a type that implements the error interface and modify the callers of `NewReadOnly` to explicitly pass the var name. I've got that working. TBD is adding unit tests and fixing the `Set` method in *pkg/eval/vars/callback.go*. At the moment I'm hard-coding a literal var name in that function so the compilation succeeds.

**Closed** 2021-02-21 11:54 UTC

**Comment by krader1961** [comment] 2021-02-22 05:51
Not to nitpick but the fix only highlight the affected var in the backtrace. It doesn't actually interpolate the var name in the error message. Which behavior is better is unclear but I, like the person who opened this question, was hoping the var name would be in the error message -- not just shown in a distinct fashion in the backtrace. Especially since there are cases, such as the updated reproducer in my previous comment, that does not highlight just the variable name. For example:

```
> try { fail } except false { put $false }
Exception: read-only variable; cannot be set
[tty 5], line 1: try { fail } except false { put $false }
```

Note that the entire statement is highlighted -- not just the `false` var name. Whereas with my rejected pull-request the error is `Exception: read-only variable builtin:false cannot be set`.
