### ISSUE TITLE
Lambda variable highlighted as red (nonexistent)

### ISSUE THREAD

**Issue by hexchain** [elves/elvish#172] opened 2016-04-05 06:12 UTC
![1459836637](https://cloud.githubusercontent.com/assets/529520/14272734/354c0284-fb38-11e5-80ff-75ae22784ed1.png)

**Comment by xiaq** [comment] 2016-09-09 23:43
It is no longer colored as red but entirely uncolored now. On the other hand, variables get a purple coloring when it is not used as the command. Interesting.

**Comment by xiaq** [comment] 2016-09-11 00:06
The reason for the aforementioned phenomena is caused by `edit.writer` not joining styles correctly, which has been fixed in 69dca19b68757ac092af38deccdf1cfe2b8e4660. Now they are red again.

**Closed** 2016-09-11 00:09 UTC
Labels: bug
