### ISSUE TITLE
Support edit:undo and edit:redo

### ISSUE THREAD

**Issue by simonrouse9461** [elves/elvish#1367] opened 2021-07-13 16:40 UTC
Recently, fish added support for undo and redo. I don't see a similar api in the "edit:" interface. I think it's a good feature to be added.

**Comment by krader1961** [comment] 2021-07-13 17:24
Dup of issue #636?

**Comment by krader1961** [comment] 2021-08-13 04:32
@simonrouse9461: Any reason this shouldn't be closed as a duplicate of issue #636?

**Comment by xiaq** [comment] 2021-08-13 10:48
Closing as duplicate

**Closed by xiaq** 2021-08-13 10:48 UTC
