### ISSUE TITLE
Terminal title setting don't work in edit:after-readline

### ISSUE THREAD

**Issue by notramo** [elves/elvish#593] opened 2018-02-11 19:28 UTC
I have a command in `edit:after-readline` that sets the terminal title: `[line]{ e:echo "\e]2;"$line"\a" }`
After the recent fixing of the after-readline hook crash, this command don't work anymore. It prints this after every command: `[bytes out] ^[]2;~^G^G^[]2;exa^G`. Does it capture the output? If the builtin `print` is used instead of the external `echo`, it does nothing (don't even prints the `[byte out...` text).
I have another command in this hook, that updates the cached Git info displayed in the prompt. This function works well.

What about replacing these hooks with the readline mode chage hooks (#550) ? I updated this issue with a new idea (simpler, but more powerful).

**Comment by zzamboni** [comment] 2018-02-11 21:23
@notramo I have a slightly different implementation which still works after the latest update. Here it is (from https://github.com/zzamboni/dot_elvish/blob/master/rc.org#dynamic-terminal-title):
```
fn set-title [title]{ print "\e]0;"$title"\e\\" }
prompt_hooks:add-before-readline {
  set-title "elvish "(tilde-abbr $pwd) > /dev/tty
}
prompt_hooks:add-after-readline [cmd]{
  set-title (re:split '\s' $cmd | take 1)" "(tilde-abbr $pwd)
}
```
Not sure if it's because of my use of `print` instead of `echo` or the slightly different escape sequence.

**Comment by notramo** [comment] 2018-02-11 21:42
Yes, tty redirecting works for me also with the builtin `print` command.
Maybe the escape sequences differ because of terminal type (mine is `xterm-256color`).

**Comment by zzamboni** [comment] 2018-02-11 21:50
I just noticed that my `before-readline` hook was still working, but `after-readline` was not because I had forgotten the redirect to `/dev/tty`. I've fixed it now and it works fine. My terminal type is also `xterm-256color`.
```
fn set-title [title]{ print "\e]0;"$title"\e\\" > /dev/tty }
prompt_hooks:add-before-readline {
  set-title "elvish "(tilde-abbr $pwd)
}
prompt_hooks:add-after-readline [cmd]{
  set-title (re:split '\s' $cmd | take 1)" "(tilde-abbr $pwd)
}
```

**Comment by zzamboni** [comment] 2018-02-12 12:14
I just noticed that printing messages from within the hooks no longer works. I'm adding this comment here because I think this is the root cause of this bug as originally reported. I noticed this from my [proxy module](https://github.com/zzamboni/elvish-modules/blob/master/proxy.org). The notifications now show up like this: `[bytes out] ^[[34mSetting proxy http://proxy.corproot.net:8079^[[m`. If I change the `echo` statement to redirect to `/dev/tty`, the notifications appear correctly again. I.e. the following doesn't work anymore:
```
echo (edit:styled "Setting proxy "$host blue)
```
but the following does:
```
echo (edit:styled "Setting proxy "$host blue) > /dev/tty
```
I'm not sure if this is intended behavior of a bug after b77b3d7846e4916f7777e7e9365de67983b8ac78. @xiaq can you clarify?

**Comment by notramo** [comment] 2018-02-12 20:55
The problem with `/dev/tty` redirect is that it isn't considered by the editor, so it can appear in a wrong place, and mess up editor output. If the command does something like terminal title changing, it isn't a big problem.

**Comment by xiaq** [comment] 2018-02-14 06:40
I consider this a bug. The problem is that when fixing the after-readline nil-deference bug I moved the calls to after-readline hooks to *just before* the editor becomes inactive, which means that their output is redirected to the notification area of the editor.

**Comment by zzamboni** [comment] 2018-02-14 07:41
@xiaq I think it would be OK (in fact, it would be a nice feature!) to have those messages shown as notifications, as long as we could get rid of the "[bytes out]" part and have them show up with formatting.

**Comment by xiaq** [comment] 2019-12-28 01:41
The after-readline hook is now run directly in the terminal, so this is now fixed.

**Closed by xiaq** 2019-12-28 01:41 UTC
Labels: c:ui, t:bug

**Comment by zzamboni** [comment] 2019-12-28 20:35
This is great news. I've started removing the `> /dev/tty` from some of my modules, and it seems to work well - much cleaner like this!
