### ISSUE TITLE
Crash on exiting file manager

### ISSUE THREAD

**Issue by Epse** [elves/elvish#853] opened 2019-08-26 13:29 UTC
Whenever I open the file manager and close it again (using `C-n`) elvish crashes. (Crashlog down below) When I have a non-directory selected, the crashlog is slightly different. Every time I get dumped into `sh` which is welcome.
This happens using latest release and current git master.

Crashlog with a directory selected:
```
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/elves/elvish/sys.DumpStack(0xa62e20, 0xc0000a0008)
	sys/dumpstack.go:10 +0x9d
github.com/elves/elvish/program/shell.rescue()
	program/shell/shell.go:66 +0xde
panic(0x911120, 0xe102f0)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/elves/elvish/eval.catch(0xc0000bd860, 0xc000184300)
	eval/frame.go:210 +0x262
panic(0x911120, 0xe102f0)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/elves/elvish/edit/edcore.(*navigation).List(0xc0001de190, 0x38, 0xc0001de190, 0x7ff45051ac88)
	edit/edcore/navigation.go:346 +0x80
github.com/elves/elvish/edit/edcore.(*editorRenderer).Render(0xc00000e260, 0xc0001de2d0)
	edit/edcore/render.go:242 +0x103b
github.com/elves/elvish/edit/ui.Render(0xa62560, 0xc00000e260, 0x112, 0xc000136960)
	edit/ui/render.go:20 +0xe9
github.com/elves/elvish/edit/edcore.(*editor).refresh(0xc0001cc000, 0xa60101, 0xc0001f0690, 0x0)
	edit/edcore/edit.go:268 +0x4af
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc0001cc000, 0xa62620, 0xc0001f0690, 0x0, 0x0, 0x0)
	edit/edcore/api.go:121 +0x24e
github.com/elves/elvish/edit/edcore.(*navigation).defaultFn(0xc0001de190, 0xc0001cc000)
	edit/edcore/navigation.go:165 +0x13f
github.com/elves/elvish/edit/edcore.initNavigation.func4()
	edit/edcore/navigation.go:65 +0x33
reflect.Value.call(0x8d7ec0, 0xc0001cf700, 0x13, 0x9a68dc, 0x4, 0x0, 0x0, 0x0, 0xc0000bd540, 0x471770, ...)
	/usr/lib/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x8d7ec0, 0xc0001cf700, 0x13, 0x0, 0x0, 0x0, 0xc0000bd500, 0xc0000bd5a8, 0x487af1)
	/usr/lib/go/src/reflect/value.go:308 +0xa4
github.com/elves/elvish/eval.(*GoFn).Call(0xc0001f09a0, 0xc000184300, 0x0, 0x0, 0x0, 0xc0001364e0, 0x984d00, 0xc0000bd818)
	eval/go_fn.go:227 +0x653
github.com/elves/elvish/eval.(*Frame).Call(0xc000184300, 0xa62620, 0xc0001f09a0, 0x0, 0x0, 0x0, 0xc0001364e0, 0x0, 0x0)
	eval/frame.go:163 +0xbb
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc0001cc000, 0xa62620, 0xc0001f09a0, 0x0, 0x0, 0x0)
	edit/edcore/api.go:115 +0x227
github.com/elves/elvish/edit/edcore.(*editor).ReadLine(0xc0001cc000, 0x0, 0x0, 0x0, 0x0)
	edit/edcore/edit.go:500 +0x1113
github.com/elves/elvish/program/shell.interact(0xc0001920c0, 0xc00013c9a0, 0xf, 0x0)
	program/shell/interact.go:62 +0x2f2
github.com/elves/elvish/program/shell.(*Shell).Main(0xc000150e80, 0xc000092170, 0x0, 0x0, 0x0)
	program/shell/shell.go:54 +0x1d2
github.com/elves/elvish/program.Main(0xc000092170, 0x1, 0x1, 0x0)
	program/program.go:123 +0x171
main.main()
	main.go:14 +0x45

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/usr/lib/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 34 [chan receive]:
github.com/elves/elvish/eval.init.13.func1()
	eval/port.go:49 +0x53
created by github.com/elves/elvish/eval.init.13
	eval/port.go:48 +0x49

goroutine 51 [chan receive]:
github.com/elves/elvish/program/shell.handleSignals.func1(0xc000088120)
	program/shell/shell.go:76 +0xb8
created by github.com/elves/elvish/program/shell.handleSignals
	program/shell/shell.go:75 +0x7c

goroutine 54 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc0001b0080)
	edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
	edit/prompt/prompt.go:69 +0x18f

goroutine 55 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc0001b0100)
	edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
	edit/prompt/prompt.go:69 +0x18f

execing recovery shell /bin/sh
sh-5.0$ exit
exit
```

Crashlog with a file selected (under the cursor):
```
function error: chdir Baofeng_BF-888_20190723.img: not a directory
~> 

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/elves/elvish/sys.DumpStack(0xa2e740, 0xc0000a0008)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/sys/dumpstack.go:10 +0x9d
github.com/elves/elvish/program/shell.rescue()
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/program/shell/shell.go:60 +0xde
panic(0x8e7ee0, 0xdbb280)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/elves/elvish/eval.catch(0xc0006098c8, 0xc00012e420)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/eval/frame.go:190 +0x262
panic(0x8e7ee0, 0xdbb280)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/elves/elvish/edit/edcore.(*navigation).List(0xc0000afdb0, 0x38, 0xc0000afdb0, 0x7fd880268270)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/edcore/navigation.go:346 +0x80
github.com/elves/elvish/edit/edcore.(*editorRenderer).Render(0xc0000ad860, 0xc0000af1d0)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/edcore/render.go:242 +0x103b
github.com/elves/elvish/edit/ui.Render(0xa2de80, 0xc0000ad860, 0x112, 0xa2ede0)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/ui/render.go:16 +0xe9
github.com/elves/elvish/edit/edcore.(*editor).refresh(0xc0001b6000, 0xa20101, 0xc0000afef0, 0x0)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/edcore/edit.go:268 +0x456
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc0001b6000, 0xa2df00, 0xc0000afef0, 0x0, 0x0, 0x0)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/edcore/api.go:121 +0x24e
github.com/elves/elvish/edit/edcore.(*navigation).defaultFn(0xc0000afdb0, 0xc0001b6000)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/edcore/navigation.go:165 +0x13f
github.com/elves/elvish/edit/edcore.initNavigation.func4()
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/edcore/navigation.go:65 +0x33
reflect.Value.call(0x8b1500, 0xc0000acf20, 0x13, 0x977255, 0x4, 0x0, 0x0, 0x0, 0xc0006095c8, 0x42d911, ...)
	/usr/lib/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x8b1500, 0xc0000acf20, 0x13, 0x0, 0x0, 0x0, 0xc0000a20c0, 0xc00006e000, 0x50)
	/usr/lib/go/src/reflect/value.go:308 +0xa4
github.com/elves/elvish/eval.(*BuiltinFn).Call(0xc0001cc140, 0xc00012e420, 0x0, 0x0, 0x0, 0xc000138390, 0x955660, 0xc000609880)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/eval/builtin_fn.go:184 +0x626
github.com/elves/elvish/eval.(*Frame).Call(0xc00012e420, 0xa2df00, 0xc0001cc140, 0x0, 0x0, 0x0, 0xc000138390, 0x0, 0x0)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/eval/frame.go:143 +0xbb
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc0001b6000, 0xa2df00, 0xc0001cc140, 0x0, 0x0, 0x0)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/edcore/api.go:115 +0x227
github.com/elves/elvish/edit/edcore.(*editor).ReadLine(0xc0001b6000, 0x0, 0x0, 0x0, 0x0)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/edcore/edit.go:500 +0xb3c
github.com/elves/elvish/program/shell.interact.func1(0xc0001521e0, 0xc000578000, 0x0, 0x0)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/program/shell/interact.go:41 +0x2f
github.com/elves/elvish/program/shell.interact(0xc0001521e0, 0xc000026a90, 0xf, 0x0)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/program/shell/interact.go:51 +0x20d
github.com/elves/elvish/program/shell.(*Shell).Main(0xc00006ce40, 0xc000092170, 0x0, 0x0, 0x0)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/program/shell/shell.go:48 +0x1a7
github.com/elves/elvish/program.Main(0xc000092170, 0x1, 0x1, 0x0)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/program/program.go:119 +0x171
main.main()
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/main.go:14 +0x45

goroutine 19 [syscall, 1 minutes]:
os/signal.signal_recv(0xa348c0)
	/usr/lib/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 4 [chan receive, 1 minutes]:
github.com/elves/elvish/eval.init.13.func1()
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/eval/port.go:49 +0x53
created by github.com/elves/elvish/eval.init.13
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/eval/port.go:48 +0x49

goroutine 21 [chan receive, 1 minutes]:
github.com/elves/elvish/program/shell.handleSignals.func1(0xc000030120)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/program/shell/shell.go:70 +0xb8
created by github.com/elves/elvish/program/shell.handleSignals
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/program/shell/shell.go:69 +0x7c

goroutine 24 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc00011e100)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/prompt/prompt.go:69 +0x18f

goroutine 25 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc00011e180)
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
	/home/e/.cache/yay/elvish/src/build/src/github.com/elves/elvish/edit/prompt/prompt.go:69 +0x18f

execing recovery shell /bin/sh
sh-5.0$ exit
exit
```

**Comment by zzamboni** [comment] 2019-08-26 13:40
I can confirm the crash on latest master  (`e2a3f2d`).

**Comment by occivink** [comment] 2019-08-26 13:52
Dupe of #627

**Comment by xiaq** [comment] 2019-12-28 02:19
Fixed.

**Closed by xiaq** 2019-12-28 02:19 UTC
