### ISSUE TITLE
crash: unexpected rune '\x1b'

### ISSUE THREAD

**Issue by rsteube** [elves/elvish#1511] opened 2022-04-01 10:16 UTC
affected version
---
0.18.0

summary
---
Slipped over my keyboard :sweat_smile: and somehow entered a rune that caused elvish to crash.

steps to reproduce
---
```sh
echo ^[<TAB>
```

log
---

```go
❯ gh api repos/cli/cli/actions/runs/^[
goroutine 1 [running]:[tty]: unexpected rune '\x1b'
src.elv.sh/pkg/sys.DumpStack()
        src.elv.sh/pkg/sys/dumpstack.go:10 +0x66
src.elv.sh/pkg/shell.handlePanic()
        src.elv.sh/pkg/shell/interact.go:141 +0x5a
panic({0x716500, 0xc0002eb2a8})
        runtime/panic.go:1038 +0x215
src.elv.sh/pkg/edit/complete.completeVariable({0x0, 0xc00029a480, 0x0}, {{0x79af60, 0xc0000a4000}, 0xc0003ee000, 0xc000033000})
        src.elv.sh/pkg/edit/complete/completers.go:149 +0x2c6
src.elv.sh/pkg/edit/complete.Complete({{0xc0000c8390, 0xc0000f6000}, 0x0}, {{0x79af60, 0xc0000a4000}, 0xc0003ee000, 0xc000033000})
        src.elv.sh/pkg/edit/complete/complete.go:91 +0x248
src.elv.sh/pkg/edit.completionStart({0x79e8c8, 0xc0000f6000}, {0x78da40, 0xc000097380}, {{0x79af60, 0xc0000a4000}, 0xc0003ee000, 0xc000033000}, 0x1)
        src.elv.sh/pkg/edit/completion.go:180 +0x171
src.elv.sh/pkg/edit.initCompletion.func4()
        src.elv.sh/pkg/edit/completion.go:267 +0x70
reflect.Value.call({0x6bae80, 0xc0000973e0, 0x48d888}, {0x72ca67, 0x4}, {0x0, 0x0, 0x4d5d27})
        reflect/value.go:543 +0x814
reflect.Value.Call({0x6bae80, 0xc0000973e0, 0x4d5d27}, {0x0, 0x0, 0x0})
        reflect/value.go:339 +0xc5
src.elv.sh/pkg/eval.(*goFn).Call(0xc0000fa380, 0xc00035d580, {0x0, 0x0, 0x0}, 0xc000077200)
        src.elv.sh/pkg/eval/go_fn.go:247 +0xb46
src.elv.sh/pkg/eval.(*Evaler).Call(0x40998d, {0x78d380, 0xc0000fa380}, {{0x0, 0x0, 0x0}, 0xc000077200, {0x7309ea, 0x10}}, {{0xc00027b4e8, ...}, ...})
        src.elv.sh/pkg/eval/eval.go:434 +0x37f
src.elv.sh/pkg/edit.callWithNotifyPorts({0x7944c0, 0xc000094540}, 0x1, {0x78d380, 0xc0000fa380}, {0x0, 0x0, 0x0})
        src.elv.sh/pkg/edit/key_binding.go:67 +0x1fb
src.elv.sh/pkg/edit.mapBindings.Handle({{0x7944c0, 0xc000094540}, 0xc0000a4000, {0xc0000ac6c0, 0x1, 0x1}}, {0xc0003d56c8, 0x40a96e}, {0x78d900, 0xc00028f990})
        src.elv.sh/pkg/edit/key_binding.go:41 +0x117
src.elv.sh/pkg/cli/tk.(*codeArea).handleKeyEvent(0xc0000f6100, {0x3d5760, 0xc0})
        src.elv.sh/pkg/cli/tk/codearea.go:297 +0xd5
src.elv.sh/pkg/cli/tk.(*codeArea).Handle(0xc0000f6000, {0x78d900, 0xc00028f988})
        src.elv.sh/pkg/cli/tk/codearea.go:172 +0x72
src.elv.sh/pkg/cli.(*app).handle(0xc0000f6000, {0x6fcc80, 0xc00028f988})
        src.elv.sh/pkg/cli/app.go:226 +0x165
src.elv.sh/pkg/cli.(*loop).Run(0xc0000cc8c0)
        src.elv.sh/pkg/cli/loop.go:129 +0x1b8
src.elv.sh/pkg/cli.(*app).ReadCode(0xc0000f6000)
        src.elv.sh/pkg/cli/app.go:475 +0x4a5
src.elv.sh/pkg/edit.(*Editor).ReadCode(0xc00000e010)
        src.elv.sh/pkg/edit/editor.go:113 +0x22
src.elv.sh/pkg/shell.interact(0xc0000a4000, {0xc00000e010, 0xc00000e018, 0xc00000e020}, 0xc0000e5d70)
        src.elv.sh/pkg/shell/interact.go:100 +0x846
src.elv.sh/pkg/shell.(*Program).Run(0xc0000778c0, {0xc00000e010, 0xc00000e018, 0xc00000e020}, {0xc00001e1e0, 0x72c7b2, 0x0})
        src.elv.sh/pkg/shell/shell.go:98 +0x2e5
src.elv.sh/pkg/prog.composite.Run({0xc00007b9c0, 0x4, 0x503eaf}, {0xc00000e010, 0xc00000e018, 0xc00000e020}, {0xc00001e1e0, 0x0, 0x0})
src.elv.sh/pkg/prog.composite.Run({0xc00007b9c0, 0x4, 0x503eaf}, {0xc00000e010, 0xc00000e018, 0xc00000e020}, {0xc00001e1e0, 0x0, 0x0})
        src.elv.sh/pkg/prog/prog.go:118 +0xc3
src.elv.sh/pkg/prog.Run({0xc00000e010, 0xc00000e018, 0xc00000e020}, {0xc00001e1e0, 0x1, 0x1}, {0x794ce0, 0xc00000c630})
        src.elv.sh/pkg/prog/prog.go:83 +0x3d4
main.main()
        src.elv.sh/cmd/elvish/main.go:18 +0x17f

goroutine 6 [chan receive, 114 minutes]:
src.elv.sh/pkg/eval.getBlackholeChan.func1()
        src.elv.sh/pkg/eval/port.go:96 +0x3a
created by src.elv.sh/pkg/eval.getBlackholeChan
        src.elv.sh/pkg/eval/port.go:95 +0x6f

goroutine 7 [syscall]:
os/signal.signal_recv()
        runtime/sigqueue.go:169 +0x98
os/signal.loop()
        os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
        os/signal/signal.go:151 +0x2c

goroutine 17 [chan receive]:

src.elv.sh/pkg/shell.initSignal.func1()
        src.elv.sh/pkg/shell/shell.go:138 +0x7f
created by src.elv.sh/pkg/shell.initSignal
        src.elv.sh/pkg/shell/shell.go:137 +0x96

goroutine 19 [chan receive]:
src.elv.sh/pkg/cli/prompt.(*Prompt).loop(0xc0000af0a0)
        src.elv.sh/pkg/cli/prompt/prompt.go:77 +0xb6
created by src.elv.sh/pkg/cli/prompt.New
        src.elv.sh/pkg/cli/prompt/prompt.go:70 +0x1cf

goroutine 20 [chan receive]:
src.elv.sh/pkg/cli/prompt.(*Prompt).loop(0xc0000af180)
        src.elv.sh/pkg/cli/prompt/prompt.go:77 +0xb6
created by src.elv.sh/pkg/cli/prompt.New
        src.elv.sh/pkg/cli/prompt/prompt.go:70 +0x1cf

runtime error: index out of range [0] with length 0

Execing recovery shell /bin/sh
sh-5.1$ [A^C
sh-5.1$ ( IFS=$'\n'; echo "${COMPREPLY[*]}"^C
sh-5.1$ ext

```

**Comment by krader1961** [comment] 2022-05-31 01:30
This is a dupe of #1530 and elvish built before the commit that introduced the bug (#e58e5a4) doesn't panic. Normally we would close the newer issue as a dupe of this one but since the newer issue has more info, and an easier reproduction, it makes more sense to close this older issue. @rsteube, can you please close this so the focus is on #1530?

**Closed** 2022-05-31 06:49 UTC
