### ISSUE TITLE
setting non-existing variable doesn't lead to an error

### ISSUE THREAD

**Issue by gergelyk** [elves/elvish#1247] opened 2021-02-23 12:26 UTC
According to the [docs](https://elv.sh/ref/language.html#set), all the variables to set must already exist. Therefore I would expect this statement to raise an error:

```
set some-non-existing-var = 123  # doesn't raise
put $some-non-existing-var       # variable seems defined
```

**Comment by krader1961** [comment] 2021-02-23 23:20
The `var` and `set` commands are brand new. The old `varname = value` syntax still works without having to declare the variable with `var`. That's why your example works. Once it becomes mandatory to declare a variable with `var` I would expect your example to fail.

**Comment by xiaq** [comment] 2021-02-23 23:28
The `set` builtin is different from the old `varname = value` form in that it should raise an error when the variable hasn't been declared, this is a bug.

**Comment by krader1961** [comment] 2021-02-24 03:39
@xiaq, I'll be curious to see how you square this circle. I assumed the current behavior is to remain compatible with the old assignment syntax. That is, to allow a sequence like this:

```
> x = y
> set x = z
```

**Comment by xiaq** [comment] 2021-02-24 10:40
> @xiaq, I'll be curious to see how you square this circle. I assumed the current behavior is to remain compatible with the old assignment syntax. That is, to allow a sequence like this:
> 
> ```
> > x = y
> > set x = z
> ```

I'm not sure what the problem is, can you elaborate?

**Comment by krader1961** [comment] 2021-02-25 04:31
> I'm not sure what the problem is, can you elaborate?

@xiaq, My expectation is that using `set` without a matching `var` is an error. That is, the legacy `x = y` syntax would not be considered equivalent to `var x = y` in order to facilitate identifying incomplete updates to the new `var`/`set` paradigm.

**Comment by xiaq** [comment] 2022-02-25 21:33
This is now fixed.

**Closed by xiaq** 2022-02-25 21:33 UTC
Labels: bug
