### ISSUE TITLE
"keys $local:" crashes Elvish

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#1343] opened 2021-06-22 23:07 UTC
This is supposed to list the names of local variables, but it crashes Elvish instead. Something wrong with variable resolution code.

**Comment by krader1961** [comment] 2021-06-25 03:46
This seems like a duplicate of issue #668.

**Comment by xiaq** [comment] 2021-06-26 10:33
> This seems like a duplicate of issue #668.

Well, crashing is a more severe issue than not supporting introspection. I went back and forth but decided to keep them separate since fixing the crash is higher priority.

**Comment by krader1961** [comment] 2021-06-27 03:29
Yes, crashing is a more severe issue but it seems to me that actually supporting introspection of the `local` namespace, and documenting same, is likely to fix the crash. It's not clear what it would mean to fix this crash but not support introspection of `$local:`. 😄

**Comment by krader1961** [comment] 2021-06-27 03:42
> It's not clear what it would mean to fix this crash but not support introspection of `$local:`.

Obviously you could explicitly disallow introspection of the `local` namespace ; making it unique in its behavior when compared to the other namespaces. Perhaps by raising a specific exception when something like `keys $local:` is executed (or simply outputting no values). That would fix this issue but would seem to be against the spirit of this issue and #668.

**Comment by xiaq** [comment] 2021-06-27 15:24
> > It's not clear what it would mean to fix this crash but not support introspection of `$local:`.
> 
> Obviously you could explicitly disallow introspection of the `local` namespace ; making it unique in its behavior when compared to the other namespaces. Perhaps by raising a specific exception when something like `keys $local:` is executed (or simply outputting no values).

Seems you answered your own question :)

> That would fix this issue but would seem to be against the spirit of this issue and #668.

Well, the spirit of this issue is that crashing when using a feature is worse than not supporting a feature.

**Closed** 2022-02-26 02:08 UTC
Labels: bug
