### ISSUE TITLE
Panic in completion filter mode hitting <tab> on no matches

### ISSUE THREAD

**Issue by kwshi** [elves/elvish#836] opened 2019-06-27 19:10 UTC
# The issue

If you enter completion mode (e.g. `cd <tab>`) and resume filtering (`<C-f>` by default), then enter some stuff so that there are no matches, then hit `<tab>` again, elvish panics.

# Steps to reproduce

`cd <tab><C-f> somegarbledstuff@)#*!./$ <tab>`

# Platform

macOS Mojave 10.14.5

# Sample output

```
runtime error: index out of range
goroutine 1 [running]:
github.com/elves/elvish/sys.DumpStack(0xc420073140, 0x1)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/sys/dumpstack.go:10 +0xa2
github.com/elves/elvish/program/shell.rescue()
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/program/shell/shell.go:60 +0xc5
panic(0x147d860, 0x17c0210)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/elves/elvish/edit/completion.(*completion).selectedCandidate(...)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/edit/completion/completion_mode.go:174
github.com/elves/elvish/edit/completion.(*completion).Replacement(0xc42015c780, 0x1573e40, 0xc42015c780, 0x1f0ebe0, 0xc42015c780)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/edit/completion/completion_mode.go:103 +0x89
github.com/elves/elvish/edit/edcore.(*editorRenderer).Render(0xc4204d3ce0, 0xc420320eb0)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/edit/edcore/render.go:183 +0x150b
github.com/elves/elvish/edit/ui.Render(0x156fc40, 0xc4204d3ce0, 0x50, 0x1570ca0)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/edit/ui/render.go:16 +0x10b
github.com/elves/elvish/edit/edcore.(*editor).refresh(0xc4201d4000, 0x1560101, 0xc4201e2dc0, 0x0)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/edit/edcore/edit.go:268 +0x2db
github.com/elves/elvish/edit/edcore.(*editor).CallFn(0xc4201d4000, 0x156fcc0, 0xc4201e2dc0, 0x0, 0x0, 0x0)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/edit/edcore/api.go:121 +0x27e
github.com/elves/elvish/edit/edcore.(*editor).ReadLine(0xc4201d4000, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/edit/edcore/edit.go:500 +0x9af
github.com/elves/elvish/program/shell.interact.func1(0x1495900, 0xc420534780, 0x15, 0x0)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/program/shell/interact.go:41 +0x2f
github.com/elves/elvish/program/shell.interact(0xc4200e3180, 0xc4200d02a0, 0x15, 0x0)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/program/shell/interact.go:51 +0x219
github.com/elves/elvish/program/shell.(*Shell).Main(0xc4201c0380, 0xc42009e170, 0x0, 0x0, 0x0)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/program/shell/shell.go:48 +0x1a7
github.com/elves/elvish/program.Main(0xc42009e170, 0x1, 0x1, 0x0)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/program/program.go:119 +0x180
main.main()
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/main.go:14 +0x45

goroutine 19 [syscall]:
os/signal.signal_recv(0x1573980)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/sigqueue.go:139 +0xa7
os/signal.loop()
	/usr/local/Cellar/go/1.10.3/libexec/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/Cellar/go/1.10.3/libexec/src/os/signal/signal_unix.go:28 +0x41

goroutine 21 [chan receive]:
github.com/elves/elvish/eval.init.13.func1()
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/eval/port.go:49 +0x53
created by github.com/elves/elvish/eval.init.13
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/eval/port.go:48 +0x49

goroutine 23 [select, locked to thread]:
runtime.gopark(0x1536218, 0x0, 0x150f0fb, 0x6, 0x18, 0x1)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc42004c750, 0xc420094300)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/signal_unix.go:549 +0x1c6
runtime.goexit()
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361 +0x1

goroutine 24 [chan receive]:
github.com/elves/elvish/program/shell.handleSignals.func1(0xc420094240)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/program/shell/shell.go:70 +0xb8
created by github.com/elves/elvish/program/shell.handleSignals
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/program/shell/shell.go:69 +0x7c

goroutine 27 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc4201ba480)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/edit/prompt/prompt.go:69 +0x1b4

goroutine 28 [chan receive]:
github.com/elves/elvish/edit/prompt.(*prompt).loop(0xc4201ba500)
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/edit/prompt/prompt.go:76 +0xd1
created by github.com/elves/elvish/edit/prompt.makePrompt
	/private/tmp/elvish-20180822-97171-hko27m/elvish-0.12/src/github.com/elves/elvish/edit/prompt/prompt.go:69 +0x1b4

execing recovery shell /bin/sh
```

**Comment by kwshi** [comment] 2019-06-27 19:12
The same error occurs with `<up arrow>` (or, with `readline-bindings`, `<C-p>`).

**Comment by zzamboni** [comment] 2019-06-29 21:52
@kwshi which version are you using? I cannot reproduce this on latest from master (v0.12-513-g0e6980a), but I remember seeing this some time ago.

**Comment by kwshi** [comment] 2019-07-01 04:12
Running `elvish --version` simply reports `0.12`.  I installed it from Homebrew, if that helps.  If it's resolved on master, then I think this can be closed since it'll just fix itself by the next release.

**Comment by zzamboni** [comment] 2019-07-01 06:46
0.12 is quite old (2018-08-01), and there have been many fixes and new features since then. I would suggest using `brew install --head elvish` to get the latest even while using Homebrew.

**Comment by xiaq** [comment] 2019-07-20 13:13
This has indeed been fixed in HEAD, closing.

**Closed by xiaq** 2019-07-20 13:13 UTC
