### ISSUE TITLE
Editor error: The parameter is incorrect.

### ISSUE THREAD

**Issue by muv1** [elves/elvish#981] opened 2020-04-22 03:13 UTC
If I try the Windows version, I get this:

~~~
 [?7h [7m⏎ [m
 [?7l [?2004hEditor error: The parameter is incorrect.
Falling back to basic line editor
~~~

**Comment by krader1961** [comment] 2020-04-22 03:24
Insufficient information, @muv1. I regularly test Elvish on MS Windows 10 and don't have any problems of the sort you document. What version of elvish did you install; i.e., what does `elvish -buildinfo` report? What did you type that lead up to that error? What does your *~/.elvish/rc.elv* file contain?

**Comment by krader1961** [comment] 2020-04-22 03:46
Also, that you are seeing ANSI terminal escape sequences is highly suspicious. What terminal are you using? How did you instantiate that elvish session?

**Comment by muv1** [comment] 2020-04-22 03:50
> What version of elvish did you install; i.e., what does `elvish -buildinfo`
> report?

~~~
Version: v0.13.1
Go version: go1.13.5
Reproducible build: true
~~~

So this question assumes that I launched from another shell like `cmd.exe`,
which I didnt. I just double clicked the executable itself. Interestingly, if
I try to launch from `cmd.exe`, I get a different error:

~~~
Cannot connect to daemon: unexpected RPC error on socket
C:\Users\Steven\AppData\Local\Temp\elvish-Steven\sock: dial tcp: missing
address
Daemon-related functions will likely not work.
~~~

> What does your `~/.elvish/rc.elv` file contain?

Dont have one of those.

> Also, that you are seeing ANSI terminal escape sequences is highly
> suspicious. What terminal are you using?

It seems this is the problem:

> only Windows 10 is supported.

<https://github.com/elves/elvish#building-elvish>

**Comment by krader1961** [comment] 2020-04-22 03:58
You didn't say what version of MS Windows you are using. I can't speak intelligently to whether elvish will work on older versions of MS Windows. In theory I would expect the shell to work on older versions; at least those release in the past decade.

Elvish is a command shell in the vein documented [here](https://en.wikipedia.org/wiki/Unix_shell). It is not a GUI program that can be launched outside of a terminal environment. If you open a `cmd.exe` terminal and execute elvish does it work without error?

**Comment by krader1961** [comment] 2020-04-22 04:04
> I just double clicked the executable itself.

Ideally that wouldn't be allowed; with a suitable error message being displayed. Or it should result in launching elvish inside a `cmd.exe` terminal session. I'm not a MS Windows programmer so I have no idea how to achieve either result. Patches are welcomed :smile: Also, I'm still curious if running elvish from a cmd.exe terminal works for you.

**Comment by muv1** [comment] 2020-04-22 04:14
> In theory I would expect the shell to work on older versions; at least those
> released in the past decade.

Thats absolutely not true. ANSI escape sequences (which Elvish clearly uses)
werent introduce to any Windows version until Windows 10 Version 1511 (2016):

<https://en.wikipedia.org/wiki/ANSI_escape_code#DOS_and_Windows>

Other Windows versions have similar capabilites via the Windows API. However
many projects are not willing to support such a thing.

> Also, I'm still curious if running elvish from a cmd.exe terminal works for
> you.

I answered that already, see above and now below:

~~~
Cannot connect to daemon: unexpected RPC error on socket
C:\Users\Steven\AppData\Local\Temp\elvish-Steven\sock: dial tcp: missing
address
Daemon-related functions will likely not work.
~~~

**Comment by krader1961** [comment] 2020-04-22 05:01
@muv1, Yes, you are correct that elvish used interactively isn't going to render well on MS Windows versions prior to Windows 10 due to the assumption of support for ANSI X3.64. Thus some functionality, such as moving the CLI cursor, won't work. But you should be able to execute an external command or a valid elvish expression AFAIK.

> I answered that already, see previous comment...

Yes, you did. I didn't notice it because of your belligerent attitude and assumption we can intuit important information you did not provide. The error you documented is due to running elvish on an old version of MS WIndows that apparently does not support UNIX domain sockets as implemented by Elvish 0.13.1. Which is to say Go v1.14.

Do you expect the pre-built elvish binary to refuse to run and complain the MS Windows version is to old? Or some other behavior?

**Comment by krader1961** [comment] 2020-04-22 05:22
@muv1, I looked at a few of the issues you have opened in other projects at little over than a month ago. Such as https://github.com/NLKNguyen/papercolor-theme/issues/148. You need to take a deep breath and chill.

**Comment by muv1** [comment] 2020-04-22 11:39
@krader1961 if you dont think this is a good issue, then close it. Or even lock it, or even block me.

But whats not appropriate is for you to go stalking me around the web, to determine if my attitude is worthy of your help.

Issues should be worked based on their merit, not on how nice someone is. Stop being a creep.

**Comment by hpwamr** [comment] 2020-04-22 14:59
> @muv1, I looked at a few of the issues you have opened in other projects at little over than a month ago. Such as [NLKNguyen/papercolor-theme#148](https://github.com/NLKNguyen/papercolor-theme/issues/148). You need to take a deep breath and chill.

Hello @krader1961 ,
Idem here https://github.com/rizonesoft/Notepad3/issues/2251#issuecomment-617605102

**Comment by xiaq** [comment] 2020-04-22 15:36
I have locked down the conversation as it is not going in a good direction for the community, and some time is needed to sort it out.

**Comment by xiaq** [comment] 2020-04-23 22:31
I reached out to @krader1961 privately and he expressed regret for his behavior. I didn't find a way to private contact @muv1.

Everyone in the Elvish community deserves to be treated respectfully, and everyone shares part of the responsibility to keep conversations civil.

The vast majority of conversations in the Elvish community are technical in nature, so the easiest and most productive way is to simply focus on the technical question itself, and steer away from the direction of ad-hominem escalation. I ask everybody on this thread to stick to that.

I will be publishing some more formal community guidelines soon.

**Comment by muv1** [comment] 2020-04-23 22:40
@xiaq thanks for unlock. I will only say a brief comment, as I dont want to
continue any negative convo. My issue with Krader was twofold. First, he didnt
carefully read all comments before posting. This require me to repeatedly convey
the same information.

I can understand if it was a large thread with my user, but it was a just opened
thread with 2 people. When I see such carelessness in practice I look down upon
it. I put great care into my code. As well, I put great care into my comments.
If I say something is so in regard to a technical comment, its because I have
typically put great time into understanding and study what I am commenting on.

Secondly I feel he acted in poor judgment, when he proceeded to troll through
previous issues I raised, completely unrelated to this repository. In addition
he even trolling without proper research in one of my other threads. Such
behavior is childish and other communities dont stand for it (Stack Exchange).

I accept his regret and welcome all to move forward in kind. In regard to
contact, you can pull a commit from a person to see the email:

https://github.com/muv1/autumn/commit/ee71e597.patch

however some users want privacy, so they can disable that too.

**Comment by xiaq** [comment] 2020-04-23 22:42
Getting back to the technical question:

@muv1 I believe you are seeing this in a Windows version that did not support VT escape sequences? I know that Windows has a console API and considered using it to support older Windows versions, but decided not to use it, mainly because it supports very few [attributes](https://docs.microsoft.com/en-us/windows/console/console-screen-buffers#character-attributes) (only 3 possible colors, for example). Eventually Windows 10 will be the only relevant Windows version anyway.

@krader1961 Elvish has never worked well on Windows < 10 (and it's debatable whether it works well on Windows 10 now :); I only documented that recently but it has always been the case.

**Comment by xiaq** [comment] 2020-04-23 22:54
@muv1 

As I said, the responsibility to keep conversation civil is on everyone.

Constructive feedback is always OK, but please do not engage in open judgements of individual's characters.

**Comment by xiaq** [comment] 2020-04-24 19:24
It seems that the issue is that Elvish does not support older Windows versions, closing.

**Closed by xiaq** 2020-04-24 19:24 UTC
