### ISSUE TITLE
Ulimit has no effect

### ISSUE THREAD

**Issue by href** [elves/elvish#856] opened 2019-08-29 14:10 UTC
Setting the  ulimit in elvish has no effect:

```shell
$ ulimit -n
> 256
ulimit -n 1024
ulimit -n
> 256
```

The following command works around the issue:
```shell
sh -c "ulimit -n 1024; exec elvish"
```

Observed on macOS 10.14.5.

**Comment by xiaq** [comment] 2019-10-16 23:08
`ulimit` has to be implemented as a builtin, and Elvish does not support that yet.

**Comment by xiaq** [comment] 2019-12-27 19:54
Duplicate of #307.

**Closed by xiaq** 2019-12-27 19:54 UTC
