### ISSUE TITLE
Key bound clear command hide prompts

### ISSUE THREAD

**Issue by mcorossigo** [elves/elvish#1238] opened 2021-02-11 14:18 UTC
Hello,
following the example in https://elv.sh/ref/edit.html#keybindings I tried `edit:insert:binding[Ctrl-L] = { clear > /dev/tty }`.

Unlike running the `clear` command, which leave me with an empty terminal with the prompt (expected behavior), using `Ctrl-L` empties completely the screen, deleting right and left prompts but still putting the cursor in the right place (where the left prompt should end).

I tried to fix by using `edit:insert:binding[Ctrl-L] = { clear > /dev/tty ; edit:redraw &full=$true }` but this makes the cursor "jump" and that gets pretty annoying.

Is seems like a bug to me, but I may be missing something.

Elvish 0.15.0
OS: Ubuntu 20.04
Terminal: Windows Terminal

Thank you.

**Comment by krader1961** [comment] 2021-02-13 03:03
Note that your second Ctrl-L binding is already present in Elvish if you run `use readline`. See http://localhost/elvish/ref/readline-binding.html. It works fine for me, with no obvious problems (including annoying behavior), when using iTerm on macOS to interact with elvish on various platforms via SSH.

I don't understand what you mean by "cursor jump". By definition the cursor will "jump" when you clear the screen unless, and only if, the cursor was already at the start of the line after the prompt and both are on the first line of the screen. Otherwise both the prompt and the cursor will jump to the top of the screen. Can you elaborate on your problem description? Perhaps by using a tool like [asciinema](https://asciinema.org/) to capture what you are seeing.

**Comment by krader1961** [comment] 2021-02-21 03:52
Ping, @mcorossigo? It is possible you have identified a real problem but it unclear what that problem is. Possibly because you are apparently running Elvish inside a WSL environment (Windows Subsystem for Linux) which may behave very differently than Elvish on UNIX like systems. Also, there have been recent updates to the Windows 10 WSL environment that improve its fidelity with respect native Ubuntu behavior.

**Comment by mcorossigo** [comment] 2021-02-21 13:34
@krader1961 sorry for not coming back sooner, it really slipped through the cracks. Anyway..

After your comment I assumed you meant `use readline-binding` documented here: https://elv.sh/ref/readline-binding.html and indeed that solved the general problem of the binding. So thank you.

The main issues was the fact that `edit:insert:binding[Ctrl-L] = { clear > /dev/tty }` was not doing what was suggested (to work like `clear`) without the full redraw.

Besides this, the cursor jump works like this:

1. write something
2. press enter
3. press `Ctrl+L`
4. the screen is complitely emptied
5. the curson appears at position (0,0)
6. the prompt is written
7. the curson appears now in the right of the left prompt

Seeing the prompt at (0,0) for ~1ms is the slighly annoying fenomenom that I do not experience when simply typing `clear`

I have tried many times to record it with asciinema, but it never appears in the record, suggesting that it happens quicker that the recording framerate of asciinema, or that it is as rendering artifact, independent of the tty content.

Sorry if I'm misunderstaning the functiong of such components, not my field of expertise.

For what concern my setup, the problem have been verified:

1. Windows Terminal on Windows 10, ssh on remote Ubuntu virtual machine
2. Windows Terminal on Windows 10, Ubuntu WSL 1
3. iTerm 2 on Macbook Pro, local
3. iTerm 2 on Macbook Pro, ssh on remote Ubuntu virtual machine

On a Macbook Pro, with iTerm2 I was consistently able to replicate the behaviour, but after enabling GPU rendering (and disabling ligatures) everything worked flawlessly.

**Comment by zzamboni** [comment] 2021-02-21 22:08
@mcorossigo I've also noticed the brief cursor jumping when using iTerm2 with ligatures. I don't find it annoying, but I do think it's an effect of iTerm2 and not something to do with Elvish, since I do not see it in Terminal.app, or in iTerm2 without ligatures. To be fair, when you enable ligatures on iTerm2 you get a warning that says "Enabling ligatures may reduce performance", so there's that.

Anyway, one way to get rid of this effect is to hide/show the cursor in the Ctrl-L binding. Using my [tty](https://github.com/zzamboni/elvish-modules/blob/master/tty.org) module, the following gets rid of the cursor-jumping effect:

```
edit:insert:binding[Ctrl-L] = { tty:hide-cursor; clear > /dev/tty ; edit:redraw &full ; tty:show-cursor }
```

Hope this helps.

**Comment by krader1961** [comment] 2021-02-22 03:52
> The main issues was the fact that edit:insert:binding[Ctrl-L] = { clear > /dev/tty } was not doing what was suggested (to work like clear) without the full redraw.

That is because when you run a command interactively the shell knows it has to render a new prompt when the command terminates. When a command is run via a key binding it is more efficient to assume the command does not alter what is displayed. Otherwise every time you pressed a key the shell would have to redraw the prompt and whatever command text, possibly spread over multiple lines, you have already entered. That would be horribly inefficient and also likely result in visual artifacts.

Note that you don't need to clear the display to see the cursor jump that is bothering you. I can see the same effect by simply pressing Enter at a prompt without entering any statement. About one time in three times I'll see the terminal render the cursor in column one of the next line before the shell renders the prompt and the cursor "jumps" to the right of the prompt. In the old days of hardware terminals like the DEC VT100 and Televideo 950 this effect was much more pronounced. This is simply the nature of the terminal UI.

**Comment by mcorossigo** [comment] 2021-02-22 15:31
> To be fair, when you enable ligatures on iTerm2 you get a warning that says "Enabling ligatures may reduce performance", so there's that.

Lacking a deep understanding of terminals, I also considered this. But the first instance of this issue happened (and keep happening) on Windows Terminal, without legatures, which is known to have GPU acceleration.

> Anyway, one way to get rid of this effect is to hide/show the cursor in the Ctrl-L binding. Using my tty module, the following gets rid of the cursor-jumping effect:

This is beautiful! I managed to make it crash pretty badly a couple times, but then I got working and it's a great solution.
I'm going to use this, so thank you!

Please notice that the reason why it bothers me (very slighlty) is that it happens in no other shell, on absolutely the same hardware. Before reporting this I tried bash, zsh and elvish. All with the  `ctrl+L` binding. Otherwaise I would have considered it normality.

> That is because when you run a command interactively the shell knows it has to render a new prompt when the command terminates. When a command is run via a key binding it is more efficient to assume the command does not alter what is displayed. Otherwise every time you pressed a key the shell would have to redraw the prompt and whatever command text, possibly spread over multiple lines, you have already entered. That would be horribly inefficient and also likely result in visual artifacts.

Interesting!

> I can see the same effect by simply pressing Enter at a prompt without entering any statement.

Literally never seen this. In fact it does not even happen with the elvish shell I'm using to test this issue.

Still, I'm faily convinced now that it is the result of quirks in the rendering engine of the various terminals, and not really an elvish issue.

Thanks for the help.

**Comment by krader1961** [comment] 2021-02-25 05:05
@mcorossigo, If there isn't anything else you expect with respect to this issue you should probably close it. If you still think Elvish behavior can be improved we need more information about the behavior you are are seeing.

Note that one reason I can reproduce your issue by simply pressing Enter is that I use a block cursor with a very high contrast to the background color of my terminal. If your terminal cursor is a vertical line, for example, it is much less likely you will notice it being rendered before Elvish writes the prompt; causing the terminal to "jump" the cursor from column one to just after the prompt string.

> Still, I'm faily convinced now that it is the result of quirks in the rendering engine of the various terminals

Sorry, but that is incorrect. What you are seeing, as best I understand your issue, is inherent to the legacy terminal model derived from hardware terminals such as the DEC VT100 and Televideo 950. Modern, ultra-fast, emulated terminals such as iTerm and alacritty can make such visual artifacts effectively invisible to humans. But those artifacts are still present; even if too brief for a typical human to notice. In other words, even the software terminals on which you don't normally see this issue might exhibit the problem when the GPU is overloaded.

**Comment by xiaq** [comment] 2021-02-26 00:12
Elvish can provide a builtin `edit:clear` function that uses the technique of hiding the cursor before clearing (what @zzamboni's code does) and bind that to Ctrl-L in readline-binding.

**Closed** 2021-02-26 00:36 UTC

**Comment by krader1961** [comment] 2021-02-26 02:49
Note that commit b2591e9 has a [bug](https://github.com/elves/elvish/commit/b2591e95a7f13fdd024a261f46a5591120afa44a#r47578718).
