### ISSUE TITLE
Add support for command name abbreviations

### ISSUE THREAD

**Issue by notramo** [elves/elvish#544] opened 2017-12-24 17:30 UTC
`edit:abbr` always replaces the given text in the command line.
Elvish should support abbreviations that works only with command names.
E.g. someone uses an abbreviation that replaces `ls` with `exa -l`. It is cool, while it is in a command name. But writing `put $false` is hard, because it replaces the `ls` pattern in it.
It could be named `edit:command-abbr`, and it should only work when writing a command name.

**Comment by xiaq** [comment] 2017-12-25 19:33
Duplicate of #394.

**Closed by xiaq** 2017-12-25 19:33 UTC
Labels: duplicate, enhancement
